# Generated by Django 3.1.4 on 2021-01-02 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeCampeonato', models.CharField(max_length=100, unique=True)),
                ('DescricaoCampeonato', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Epoca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnoInicial', models.IntegerField(default=0)),
                ('AnoFinal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeEquipa', models.CharField(max_length=30)),
                ('Descricao', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='FaixaEtaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FaixaEtaria', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GeneroDescricao', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimeiroNome', models.CharField(max_length=30)),
                ('UltimoNome', models.CharField(max_length=30)),
                ('Idade', models.IntegerField()),
                ('DataNascimento', models.DateField()),
                ('Morada', models.CharField(max_length=100)),
                ('Telemovel', models.CharField(max_length=9)),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modalidade', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.equipa')),
                ('Jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.jogador')),
                ('Jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.jogo')),
            ],
            options={
                'unique_together': {('Jogador', 'Equipa', 'Jogo')},
            },
        ),
        migrations.CreateModel(
            name='TipoAcaoDisciplinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoAcaoDisciplinar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPontuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoPontuacao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSubstituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoSubstituicao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.participante')),
                ('TipoSubstituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.tiposubstituicao')),
            ],
        ),
        migrations.CreateModel(
            name='Pontos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pontos', models.IntegerField(default=0)),
                ('Participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.participante')),
                ('TipoPontuacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.tipopontuacao')),
            ],
        ),
        migrations.AddField(
            model_name='equipa',
            name='FaixaEtaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.faixaetaria'),
        ),
        migrations.AddField(
            model_name='equipa',
            name='Modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.modalidade'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='Epoca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.epoca'),
        ),
        migrations.CreateModel(
            name='AcaoDisciplinar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.participante')),
                ('TipoAcaoDisciplinar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.tipoacaodisciplinar')),
            ],
        ),
        migrations.CreateModel(
            name='EquipaJogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.equipa')),
                ('Jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GrupoDesportivo.jogador')),
            ],
            options={
                'unique_together': {('Jogador', 'Equipa')},
            },
        ),
    ]
